server:
  port: 8089

spring:
  application:
    name: VOITURE
  datasource:
    url: jdbc:mysql://localhost:3306/voiture-ms-ace
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update